name = "void?@sodium"
author = "qIMIXERIp"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9da536b497ec839e927e8676f31b6d97c9ce0d4c4856fc2d5b762315125ec4ea"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
