name = "void?@sodium"
author = "qIMIXERIp"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ceb35d586942a9914ba76703968003f13c51a70fb2fd9fdace9495a82d622c0"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
