name = "void?@sodium"
author = "qIMIXERIp"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60c33e16b2b18ca16733afdccea0888bb95f78b07e0cafd9871bf2f9c1956aad"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
